language: generic

dist: focal

# Setup anchors to be used by the jobs as needed. The Travis CI linter gives
# '[warn] on root: unknown key "os_setups"', could not find a way
# to fix it.
os_setups:
  gcc10_setup: &gcc10
    os: linux
    compiler: gcc
    addons:
      apt:
        packages:
          - python3-pip
          - g++-10
          - valgrind
  clang11_setup: &clang11
    os: linux
    compiler: clang
    addons:
      apt:
        sources:
          - sourceline: 'ppa:mhier/libboost-latest'
          - sourceline: 'deb http://apt.llvm.org/focal/ llvm-toolchain-focal-11 main'
            key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
        packages:
          - python3-pip
          - boost1.73
          - clang-11
          - clang-tidy-11
          - clang-tools-11
          - llvm-11-dev
          - lld-11
          - valgrind
  macos_setup: &macos
    os: osx
    osx_image: xcode12.2
    compiler: clang
    addons:
      homebrew:
        packages:
          - cmake
          - cppcheck
        update: true
  coverage_setup: &coverage
    os: osx
    osx_image: xcode12.2
    compiler: gcc
    addons:
      homebrew:
        packages:
          - cmake
          - gcc
          - cpanm
        update: true

env:
  global:
    - SANITIZE=OFF
    - SANITIZE_THREAD=OFF
    - SCAN_BUILD=
    - COVERAGE=OFF
    - STATIC_ANALYSIS=OFF

matrix:
  include:
    - name: "GCC 10 Release"
      <<: *gcc10
      env:
        - MATRIX_EVAL="CC=gcc-10 && CXX=g++-10" BUILD_TYPE=Release
    - name: "GCC 10 Release with ASan/UBSan"
      <<: *gcc10
      env:
        - MATRIX_EVAL="CC=gcc-10 && CXX=g++-10" BUILD_TYPE=Release SANITIZE=ON
    - name: "GCC 10 Release with TSan/UBSan"
      <<: *gcc10
      env:
        - MATRIX_EVAL="CC=gcc-10 && CXX=g++-10" BUILD_TYPE=Release SANITIZE_THREAD=ON
    - name: "GCC 10 Debug"
      <<: *gcc10
      env:
        - MATRIX_EVAL="CC=gcc-10 && CXX=g++-10" BUILD_TYPE=Debug
    - name: "GCC 10 Debug with ASan/UBSan"
      <<: *gcc10
      env:
        - MATRIX_EVAL="CC=gcc-10 && CXX=g++-10" BUILD_TYPE=Debug SANITIZE=ON
    - name: "GCC 10 Debug with TSan/UBSan"
      <<: *gcc10
      env:
        - MATRIX_EVAL="CC=gcc-10 && CXX=g++-10" BUILD_TYPE=Debug SANITIZE_THREAD=ON
    - name: "GCC 10 static analysis Release"
      <<: *gcc10
      env:
        - MATRIX_EVAL="CC=gcc-10 && CXX=g++-10" BUILD_TYPE=Release STATIC_ANALYSIS=ON
    - name: "GCC 10 static analysis Debug"
      <<: *gcc10
      env:
        - MATRIX_EVAL="CC=gcc-10 && CXX=g++-10" BUILD_TYPE=Debug STATIC_ANALYSIS=ON
    - name: "clang 11 Release"
      <<: *clang11
      env:
        - MATRIX_EVAL="CC=clang-11 && CXX=clang++-11" BUILD_TYPE=Release
    - name: "clang 11 Release with ASan/UBSan"
      <<: *clang11
      env:
        - MATRIX_EVAL="CC=clang-11 && CXX=clang++-11" BUILD_TYPE=Release SANITIZE=ON
    - name: "clang 11 Release with TSan/UBSan"
      <<: *clang11
      env:
        - MATRIX_EVAL="CC=clang-11 && CXX=clang++-11" BUILD_TYPE=Release SANITIZE_THREAD=ON
    - name: "clang 11 Debug"
      <<: *clang11
      env:
        - MATRIX_EVAL="CC=clang-11 && CXX=clang++-11" BUILD_TYPE=Debug
    - name: "clang 11 Debug with ASan/UBSan"
      <<: *clang11
      env:
        - MATRIX_EVAL="CC=clang-11 && CXX=clang++-11" BUILD_TYPE=Debug SANITIZE=ON
    - name: "clang 11 Debug with TSan/UBSan"
      <<: *clang11
      env:
        - MATRIX_EVAL="CC=clang-11 && CXX=clang++-11" BUILD_TYPE=Debug SANITIZE_THREAD=ON
    - name: "clang 11 static analysis Release"
      <<: *clang11
      env:
        - MATRIX_EVAL="CC=clang-11 && CXX=clang++-11" BUILD_TYPE=Release SCAN_BUILD=scan-build-11
    - name: "clang 11 static analysis Debug"
      <<: *clang11
      env:
        - MATRIX_EVAL="CC=clang-11 && CXX=clang++-11" BUILD_TYPE=Debug SCAN_BUILD=scan-build-11
    - name: "XCode 12.2 Release"
      <<: *macos
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++" BUILD_TYPE=Release
    - name: "XCode 12.2 Release with ASan/UBSan"
      <<: *macos
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++" BUILD_TYPE=Release SANITIZE=ON
    - name: "XCode 12.2 Release with TSan/UBSan"
      <<: *macos
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++" BUILD_TYPE=Release SANITIZE_THREAD=ON
    - name: "XCode 12.2 Debug"
      <<: *macos
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++" BUILD_TYPE=Debug
    - name: "XCode 12.2 Debug with ASan/UBSan"
      <<: *macos
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++" BUILD_TYPE=Debug SANITIZE=ON
    - name: "XCode 12.2 Debug with TSan/UBSan"
      <<: *macos
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++" BUILD_TYPE=Debug SANITIZE_THREAD=ON
    - name: "Debug coverage"
      <<: *coverage
      env:
        - MATRIX_EVAL="CC=gcc-10 && CXX=g++-10" BUILD_TYPE=Debug COVERAGE=ON
    - name: "Release coverage"
      <<: *coverage
      env:
        - MATRIX_EVAL="CC=gcc-10 && CXX=g++-10" BUILD_TYPE=Release COVERAGE=ON

before_install:
  - eval "${MATRIX_EVAL}"

install:
  - pip3 install --user $USER cpplint

script:
  - mkdir build
  - cd build
  - EXTRA_CMAKE_OPTIONS=""
  - sudo rm -rf /usr/local/clang-7.0.0
  - if [[ "$CC" == "clang-11" ]]; then
      sudo update-alternatives --install /usr/bin/clang-tidy clang-tidy /usr/bin/clang-tidy-11 50;
      sudo update-alternatives --install /usr/bin/ld ld /usr/bin/lld-11 50;
    fi
  - if [[ "$CC" == "gcc-10" && "$COVERAGE" == "ON" ]]; then
      set -e;
      sudo cpanm install JSON;
      brew install lcov;
      EXTRA_CMAKE_OPTIONS+="-DGCOV_PATH=/usr/local/bin/gcov-10 ";
    fi
  - cmake .. -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DCMAKE_C_COMPILER=${CC} -DCMAKE_CXX_COMPILER=${CXX} -DSANITIZE=${SANITIZE} -DSANITIZE_THREAD=${SANITIZE_THREAD} -DCOVERAGE=${COVERAGE} -DSTATIC_ANALYSIS=${STATIC_ANALYSIS} ${EXTRA_CMAKE_OPTIONS}
  - if [[ ! -z "${SCAN_BUILD}" ]]; then
      ${SCAN_BUILD} --status-bugs -stats -analyze-headers --force-analyze-debug-code make -j3;
      travis_terminate 0;
    fi
  - if [[ "$STATIC_ANALYSIS" == "ON" ]]; then
      make -j2;
      travis_terminate 0;
    fi
  - make -j3
  - if [[ "$COVERAGE" == "OFF" ]]; then
      ctest -j3 -V;
      echo "Benchmark runs (for benchmark correctness, not performance!)";
      make quick_benchmarks;
    else
      set -e;
      make -j3 coverage;
      bash <(curl -s https://codecov.io/bash) -f coverage-coverage.info || echo "Codecov did not collect coverage reports";
    fi
  - if [[ "$SANITIZE" == "OFF" && "$SANITIZE_THREAD" == "OFF" && "$COVERAGE" == "OFF" && "$TRAVIS_OS_NAME" != "osx" ]]; then
      make valgrind;
    fi
