version: 2.1

jobs:
  build:
    parameters:
      build_type:
        type: enum
        enum: ["Debug", "Release"]
      compiler:
        type: enum
        enum: ["clang", "gcc"]
      asan:
        type: boolean
        default: false
      tsan:
        type: boolean
        default: false
      ubsan:
        type: boolean
        default: false
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
      - checkout
      - run:
          name: Checkout submodules
          command: git submodule update --init
      - run:
          name: Installing dependencies (common)
          command: |
            sudo add-apt-repository -y 'ppa:mhier/libboost-latest'
            sudo apt-get update
            sudo apt-get install -y boost1.74
      - when:
          condition:
            equal: [ "gcc", << parameters.compiler >> ]
          steps:
            - run:
                name: Installing dependencies (GCC)
                command: |
                  sudo add-apt-repository -y 'ppa:ubuntu-toolchain-r/test'
                  sudo apt-get update
                  sudo apt-get install -y g++-11
      - when:
          condition:
            equal: [ "clang", << parameters.compiler >> ]
          steps:
            - run:
                name: Installing dependencies (LLVM common)
                command: |
                  curl 'https://apt.llvm.org/llvm-snapshot.gpg.key' \
                    | sudo apt-key add -
                  echo \
                    'deb http://apt.llvm.org/focal/ llvm-toolchain-focal-14 main' \
                    | sudo tee -a /etc/apt/sources.list
                  sudo apt-get update
                  sudo apt-get install -y clang-14 clang-tidy-14
      - when:
          condition:
            and:
              - equal: [ "clang", << parameters.compiler >> ]
              - equal: [ "Release", << parameters.build_type >> ]
          steps:
            - run:
                name: Installing dependencies (LLVM Release)
                command: |
                  sudo apt-get install -y libomp5-14 llvm-14 lld-14
      - run:
          name: Create build environment
          command: mkdir build
      - run:
          name: Configure CMake
          working_directory: build
          command: |
            readonly BUILD_TYPE=<< parameters.build_type >>
            readonly COMPILER=<< parameters.compiler >>
            readonly ASAN=<< parameters.asan >>
            readonly TSAN=<< parameters.tsan >>
            readonly UBSAN=<< parameters.ubsan >>
            if [[ $COMPILER == "gcc" ]]; then
              export CC=gcc-11
              export CXX=g++-11
              EXTRA_CMAKE_ARGS=()
            elif [[ $COMPILER == "clang" ]]; then
              export CC=clang-14
              export CXX=clang++-14
              if [[ $BUILD_TYPE == "Release" ]]; then
                EXTRA_CMAKE_ARGS=(\
                  "-DLLVMAR_EXECUTABLE=/usr/bin/llvm-ar-14" \
                  "-DLLVMNM_EXECUTABLE=/usr/bin/llvm-nm-14" \
                  "-DLLVMRANLIB_EXECUTABLE=/usr/bin/llvm-ranlib-14")
              else
                EXTRA_CMAKE_ARGS=()
              fi
              EXTRA_CMAKE_ARGS=("${EXTRA_CMAKE_ARGS[@]}" \
                  "-DCLANG_TIDY_EXE=/usr/bin/clang-tidy-14")
            fi
            cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DFATAL_WARNINGS=ON \
              -DSANITIZE_ADDRESS=$ASAN -DSANITIZE_THREAD=$TSAN \
              -DSANITIZE_UB=$UBSAN "${EXTRA_CMAKE_ARGS[@]}"
      - run:
          name: Build
          working_directory: build
          command: make -j3
      - run:
          name: Correctness test
          working_directory: build
          command: ctest -j3 -V
      - when:
          condition:
            not:
              and:
                - << parameters.asan >>
                - equal: [ "Debug", << parameters.build_type >> ]
          steps:
            - run:
                name: Benchmark correctness test
                working_directory: build
                command: make quick_benchmarks
      - when:
          condition:
            not:
              or:
                - << parameters.asan >>
                - << parameters.tsan >>
                - << parameters.ubsan >>
          steps:
            - run:
                name: Valgrind test
                working_directory: build
                command: |
                  sudo apt-get install -y valgrind
                  make valgrind

workflows:
  build:
    jobs:
      - build:
          name: GCC 11 Debug
          build_type: Debug
          compiler: gcc
      - build:
          name: GCC 11 Debug with ASan
          build_type: Debug
          compiler: gcc
          asan: true
      - build:
          name: GCC 11 Debug with TSan
          build_type: Debug
          compiler: gcc
          tsan: true
      - build:
          name: GCC 11 Debug with UBSan
          build_type: Debug
          compiler: gcc
          ubsan: true
      - build:
          name: GCC 11 Release
          build_type: Release
          compiler: gcc
      - build:
          name: GCC 11 Release with ASan
          build_type: Release
          compiler: gcc
          asan: true
      - build:
          name: GCC 11 Release with TSan
          build_type: Release
          compiler: gcc
          tsan: true
      - build:
          name: GCC 11 Release with UBSan
          build_type: Release
          compiler: gcc
          ubsan: true
      - build:
          name: clang 14 Debug
          build_type: Debug
          compiler: clang
      - build:
          name: clang 14 Debug with ASan
          build_type: Debug
          compiler: clang
          asan: true
      - build:
          name: clang 14 Debug with TSan
          build_type: Debug
          compiler: clang
          tsan: true
      - build:
          name: clang 14 Debug with UBSan
          build_type: Debug
          compiler: clang
          ubsan: true
      - build:
          name: clang 14 Release
          build_type: Release
          compiler: clang
      - build:
          name: clang 14 Release with ASan
          build_type: Release
          compiler: clang
          asan: true
      - build:
          name: clang 14 Release with TSan
          build_type: Release
          compiler: clang
          tsan: true
      - build:
          name: clang 14 Release with UBSan
          build_type: Release
          compiler: clang
          ubsan: true
