version: 2.1

jobs:
  build:
    parameters:
      build_type:
        type: string
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
      - checkout
      - run:
          name: Checkout submodules
          command: git submodule update --init
      - run:
          name: Installing dependencies
          command: |
            sudo add-apt-repository -y 'ppa:ubuntu-toolchain-r/test'
            sudo add-apt-repository -y 'ppa:mhier/libboost-latest'
            sudo apt-get update
            sudo apt-get install -y boost1.74 g++-11 valgrind
      - run:
          name: Create build environment
          command: mkdir build
      - run:
          name: Configure CMake
          working_directory: build
          command: |
            export CC=gcc-11
            export CXX=g++-11
            cmake .. -DCMAKE_BUILD_TYPE=<< parameters.build_type >>
      - run:
          name: Build
          working_directory: build
          command: make -j3
      - run:
          name: Correctness test
          working_directory: build
          command: ctest -j3 -V
      - run:
          name: Benchmark correctness test
          working_directory: build
          command: make quick_benchmarks
      - run:
          name: Valgrind test
          working_directory: build
          command: make valgrind

workflows:
  build:
    jobs:
      - build:
          name: Debug
          build_type: Debug
      - build:
          name: Release
          build_type: Release
