name: clang-format check

on: push

jobs:
  formatting-check:
    name: clang-format check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run clang-format check
      uses: jidicula/clang-format-action@v4.4.1
      with:
        clang-format-version: '13'
