---
name: msvc-static-analysis

on: [push]

jobs:
  analyze:
    name: Analyze
    runs-on: windows-2022

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: MSVC Static Analysis Release
            preset: "msvc-static-analysis-release"

          - name: MSVC Static Analysis Debug
            preset: "msvc-static-analysis-debug"

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install Boost
        uses: MarkusJx/install-boost@v2.1.0
        id: install-boost
        with:
          boost_version: 1.78.0
          platform_version: 2019
          toolset: msvc

      - name: Setup command line tools
        uses: ilammy/msvc-dev-cmd@v1

      - name: Configure CMake
        run: cmake --preset "${{ matrix.preset }}"
        env:
          BOOST_ROOT: ${{ steps.install-boost.outputs.BOOST_ROOT }}

      - name: Run MSVC Code Analysis
        uses: microsoft/msvc-code-analysis-action@main
        # Provide a unique ID to access the sarif output path
        id: run-analysis
        with:
          cmakeBuildDirectory: "./build/${{ matrix.preset }}"
          ruleset: NativeRecommendedRules.ruleset
          ignoredPaths: ${{ github.workspace }}/3rd_party

      - name: Upload SARIF to GitHub
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: ${{ steps.run-analysis.outputs.sarif }}

      - name: Upload SARIF as an Artifact
        uses: actions/upload-artifact@v2
        with:
          name: sarif-file
          path: ${{ steps.run-analysis.outputs.sarif }}
